[package]
name = "hundred_trees_rust"
version = "0.1.0"
authors = ["luojia65 <me@luojia.cc>"]
edition = "2018"

[dependencies]

[dependencies.luos_memory_sandbox]
version = "0.0.1"
path = "C:/Users/luojia/Projects/LuosSandboxes"
